### ISSUE TITLE
Cant get Botlist

### ISSUE THREAD

**Issue by bjoerns1983** [lformella/xdcc-grabscher#1]
I am using the current Version of XG.
The Problem is that in most IRC Channels i dont get a Botlist.
For example in channel #gax on irc.otakubox.net, althought XG connects to the channel (checked it by a second client).

I am using xg on my private Server (console, web access) with debian squeeze.

**Comment by lformella** [comment]
Already read it on my webside ;) but i'am currently moving and got no time to check these issue. Hold on 3-4 weeks and i'll check this!

**Comment by lformella** [comment]
Ich schreib einfach mal auf deutsch :-)
Ich hab mich mal mit Colloquy (Irc Prog) auf den Server und Channel verbunden und das Problem ist, das die Bots dort keine Pakete direkt in den Channel posten. Statt dessen muss man mit "!list" in den Channel, bzw. "/msg bot xdcc list" an den enstprechenden Bot, die Pakete anfragen. Das kann XG aber nicht, sondern benutzt nur die einfache Variante, in dem es die Paketbeschreibungen direkt aus dem Channel liest. Leider sind auch nicht überall die Befehle !list und co. erlaubt, so dass man das per default einbauen könnte. In manchen Channels wird man für sowas gekickt und somit müsste man das nur in bestimmten Channels manuell erlauben können. Diese Möglichkeit ist aber (noch) nicht vorhanden, wäre schon eine größere Sache und lässt sich nicht mal eben fix rein hacken. Ich nehm das als Featurerequest mal mit, allerdings ohne Zusage wann und ob es überhaupt jemals kommt ;-)

**Comment by bjoerns1983** [comment]
Kann man in XG denn vielleicht eine möglichkeit einbauen damit XG ein Paket nach Angabe der Paketnummer und des Bots downloaded?
So könnte man das Listing umgehen, das wär zwar nicht ganz so komfortabel, aber egal.

**Comment by lformella** [comment]
Diese von dir beschriebene Möglichkeit, wird es in Version 0.9 geben. Bzw. werde ich ich die externe Suche von http://xg.bitpir.at einbinden und damit das Benutzen von xdcc:// Links ermöglichen :)
