### ISSUE TITLE
Probleme beim starten unter raspbmc (Linux)

### ISSUE THREAD

**Issue by jingx23** [lformella/xdcc-grabscher#12]
Beim Aufruf des Webservers tritt folgender Fehler auf:

0:XG.Server.Plugin.General.Webserver.BrowserConnection.StartRun(/index.html)
System.ArgumentOutOfRangeException: Argument is out of range.
  at System.Globalization.DateTimeFormatInfo.GetAbbreviatedDayName (DayOfWeek dayofweek) [0x00000] in <filename unknown>:0 
  at System.DateTimeUtils.ToString (DateTime dt, Nullable`1 utc_offset, System.String format, System.Globalization.DateTimeFormatInfo dfi) [0x00000] in <filename unknown>:0 
  at System.DateTimeUtils.ToString (DateTime dt, System.String format, System.Globalization.DateTimeFormatInfo dfi) [0x00000] in <filename unknown>:0 
  at System.DateTime.ToString (System.String format, IFormatProvider provider) [0x00000] in <filename unknown>:0 
  at System.Net.HttpListenerResponse.SendHeaders (Boolean closing, System.IO.MemoryStream ms) [0x00000] in <filename unknown>:0 
  at System.Net.ResponseStream.GetHeaders (Boolean closing) [0x00000] in <filename unknown>:0 
  at System.Net.ResponseStream.Write (System.Byte[] buffer, Int32 offset, Int32 count) [0x00000] in <filename unknown>:0 
  at XG.Server.Plugin.General.Webserver.BrowserConnection.WriteToStream (System.Byte[] aData) [0x00000] in <filename unknown>:0 
  at XG.Server.Plugin.General.Webserver.BrowserConnection.WriteToStream (System.String aData) [0x00000] in <filename unknown>:0 
  at XG.Server.Plugin.General.Webserver.BrowserConnection.StartRun () [0x00000] in <filename unknown>:0 

Folgende Mono Pakete sind installiert:
libmono-corlib4.0-cil               install
libmono-csharp4.0-cil               install
libmono-data-tds4.0-cil             install
libmono-i18n-west4.0-cil            install
libmono-i18n4.0-cil             install
libmono-microsoft-csharp4.0-cil         install
libmono-posix4.0-cil                install
libmono-security4.0-cil             install
libmono-sqlite4.0-cil               install
libmono-system-configuration4.0-cil     install
libmono-system-core4.0-cil          install
libmono-system-data4.0-cil          install
libmono-system-drawing4.0-cil           install
libmono-system-enterpriseservices4.0-cil    install
libmono-system-runtime-serialization4.0-cil install
libmono-system-security4.0-cil          install
libmono-system-transactions4.0-cil      install
libmono-system-web-applicationservices4.0-cil   install
libmono-system-web-services4.0-cil      install
libmono-system-web4.0-cil           install
libmono-system-xml-linq4.0-cil          install
libmono-system-xml4.0-cil           install
libmono-system4.0-cil               install
libmono-web4.0-cil              install
mono-4.0-gac                    install
mono-dmcs                   install
mono-gac                    install
mono-runtime                    install

Hast du eine Idee woran das liegen kann? Irgendwie scheint er die Datei nicht zu finden bzw. kann es sein, dass die Resourcen nicht extrahiert werden?

P.s.: Würde mich freuen wenn du mir hier weiterhelfen kannst, die Software macht nen guten Eindruck ;).

**Comment by Strubbl** [comment]
Vielleicht sind die mono Pakete zu alt, wenn raspbmc auf Debian basiert?
Ansonsten wäre das ja mal cool, wenn das Projekt unter arm baut.

**Comment by lformella** [comment]
Welche XG Version verwendest du denn? Und hast du die selbst kompiliert?

**Comment by jingx23** [comment]
Ist die 1.1.1 Version für Linux aus dem Download Bereich also keine selbstkompilierte Version. Wird das html zeugs eigentlich auch in .config entpackt oder ieht ers sich das aus der xgsnapshots Datei? Hab leider noch nicht die Zeit gefunden mich etwas in den Quellcode einzulesen.

**Comment by Strubbl** [comment]
Was gibt in deinem raspbmc `uname -a` zurück? Die Downloadversion dürfte ja für x86 kompiliert sein und nicht für arm.

**Comment by jingx23** [comment]
Uname gibt folgendes zurück:
Linux raspbmc 3.6.7 #1 PREEMPT Tue Nov 20 23:18:55 UTC 2012 armv6l GNU/Linux

Ich dachte eigentlich bei .net ist es ähnlich wie bei java, sprich das die Programme in einer vm laufen. Nur das es bei .net wichtig ist ob unter mono oder mit dem .net framework kompiliert. Aber ich könnte natürlich auch probieren den Quellcode auf dem Raspberry mit dem arm prozi kompilieren.

**Comment by lformella** [comment]
Mono und .Net sollen binär kompatibel sein, allerdings baue ich XG immer auf dem entsprechenden Ziel OS - alleine schon weil unter Windows am Ende ein Setup raus fällt und es eins, zwei Stellen mit einer bedingten Kompilierung gibt. Die Kompilate auf dem selben OS sollten allerdings gleich sein, sprich es müssten die gleichen Binaries raus kommen, auch wenn du es auf Arm kompilierst. Allerdings tendieren meine Erfahrungen mit Arm gegen Null ;-)

Die Zeile an der die Exception fliegt ist offensichtlich diese hier:
https://github.com/lformella/xdcc-grabscher/blob/525052de67566bad64ed04ba98c91aa5cca51785/Server.Plugin.General.Webserver/BrowserConnection.cs#L444
Allerdings ist mir nicht ganz klar warum. Funktioniert denn die Version auf deiner "richtigen" Linux Kiste oder passiert da das gleiche? Es könnte sich auch um einen Fehler in mono selbst handeln - mir stürzt XG auch ab und zu mal mit nem Segfault und nem mono Stacktrace dazu ab.

**Comment by jingx23** [comment]
Erstmal danke für die Unterstützung, scheint wirklich so als sei es ein Fehler in Mono selbst. Ich habe jetzt mal als .NET noob probiert XG auf dem raspberry zu kompilieren, dabei tritt folgender Fehler auf "System.DivideByZeroException: Division by zero at System.DateTimeUtils.ToString.....". Das hat mich stutzig gemacht, da hier die DateTime Funktion nun auch abkachelt. Nach ein bisschen googlen stellt sich wohl heraus, dass mono auf der raspberry platform noch ein paar problemchen hat, gerade mit hard float distros.
(http://www.raspberrypi.org/phpBB3/viewtopic.php?f=34&t=25690)

Vielleicht reicht es mir heute abend noch eine soft float distro zu prüfen. Ich werde berichten wenn es was neues gibt ;).

**Comment by lformella** [comment]
Falls du XG selbst kompilierst, dann achte darauf das Tag v1.1.1 zu nehmen, da ich im Trunk momentan mit Websockets experimentiere und das noch nicht zu 100% tüffig ist...

**Comment by jingx23** [comment]
Kurze Rückmeldung, ich bin jetzt mal zum testen gekommen => Es liegt doch an den floating points mono funzt noch nicht für armhf (hard-float). Mit der soft-float Variante von Debian “wheezy” die es auf der raspberry download seite gibt funzt mono und somit das linux XG Paket einwandfrei.
