### ISSUE TITLE
provide compiled binaries

### ISSUE THREAD

**Issue by Schabernack** [lformella/xdcc-grabscher#13]
Since Github removed the Downloads function for every project there is no way to get a current version despite compiling it yourself.

Perhaps you can link to a more recent version on your homepage?

**Comment by akrinke** [comment]
The downloads are still there, just the link is missing:
https://github.com/lformella/xdcc-grabscher/downloads

**Comment by Schabernack** [comment]
thanks. but the link will be invalid sooner or later. Github announcement says the downloads are accessible 90, then it is taken offline.

**Comment by akrinke** [comment]
Yes, it's no long term solution.

**Comment by lformella** [comment]
I linked the 1.1.1 binaries on the download page on my homepage and will host the next releases myself.
