### ISSUE TITLE
settings.xml is not working

### ISSUE THREAD

**Issue by hrvstr** [lformella/xdcc-grabscher#14]
I am using XG 2.0 on Windows 8 Pro x64.
I modified the settings.xml located in .../AppData/Roaming/XG. I for example changed the password for the WebGUI but when I go "host:5556" i only can login using the default password "xgisgreat". 

The ServerCMD gives me following errors:

04-06-2013 12:14:26,938 FATAL [960] 0:XG.Server.Plugin.General.Webserver.Browser
Connection.StartRun(/apple-touch-icon-144x144-precomposed.png)
System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinst
anz festgelegt.
   bei XG.Server.Plugin.General.Webserver.BrowserConnection.WriteToStream(Byte[]
 aData)
   bei XG.Server.Plugin.General.Webserver.BrowserConnection.StartRun()
04-06-2013 12:14:27,359 FATAL [961] 0:XG.Server.Plugin.General.Webserver.Browser
Connection.StartRun(/apple-touch-icon-144x144.png)
System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinst
anz festgelegt.
   bei XG.Server.Plugin.General.Webserver.BrowserConnection.WriteToStream(Byte[]
 aData)
   bei XG.Server.Plugin.General.Webserver.BrowserConnection.StartRun()
04-06-2013 12:14:27,437 FATAL [962] 0:XG.Server.Plugin.General.Webserver.Browser
Connection.StartRun(/apple-touch-icon-precomposed.png)
System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinst
anz festgelegt.
   bei XG.Server.Plugin.General.Webserver.BrowserConnection.WriteToStream(Byte[]
 aData)
   bei XG.Server.Plugin.General.Webserver.BrowserConnection.StartRun()
04-06-2013 12:14:27,468 FATAL [963] 0:XG.Server.Plugin.General.Webserver.Browser
Connection.StartRun(/apple-touch-icon.png)
System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinst
anz festgelegt.
   bei XG.Server.Plugin.General.Webserver.BrowserConnection.WriteToStream(Byte[]
 aData)
   bei XG.Server.Plugin.General.Webserver.BrowserConnection.StartRun()
04-06-2013 12:14:39,262 FATAL [995] 0:XG.Server.Plugin.General.Webserver.Browser
Connection.StartRun(/apple-touch-icon-144x144-precomposed.png)
System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinst
anz festgelegt.
   bei XG.Server.Plugin.General.Webserver.BrowserConnection.WriteToStream(Byte[]
 aData)
   bei XG.Server.Plugin.General.Webserver.BrowserConnection.StartRun()
04-06-2013 12:14:39,293 FATAL [996] 0:XG.Server.Plugin.General.Webserver.Browser
Connection.StartRun(/apple-touch-icon-144x144.png)
System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinst
anz festgelegt.
   bei XG.Server.Plugin.General.Webserver.BrowserConnection.WriteToStream(Byte[]
 aData)
   bei XG.Server.Plugin.General.Webserver.BrowserConnection.StartRun()
04-06-2013 12:14:39,309 FATAL [997] 0:XG.Server.Plugin.General.Webserver.Browser
Connection.StartRun(/apple-touch-icon-precomposed.png)
System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinst
anz festgelegt.
   bei XG.Server.Plugin.General.Webserver.BrowserConnection.WriteToStream(Byte[]
 aData)
   bei XG.Server.Plugin.General.Webserver.BrowserConnection.StartRun()
04-06-2013 12:14:39,340 FATAL [998] 0:XG.Server.Plugin.General.Webserver.Browser
Connection.StartRun(/apple-touch-icon.png)
System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinst
anz festgelegt.
   bei XG.Server.Plugin.General.Webserver.BrowserConnection.WriteToStream(Byte[]
 aData)
   bei XG.Server.Plugin.General.Webserver.BrowserConnection.StartRun()

**Comment by lformella** [comment]
Where did you get the setup binary? This error (apple-touch-icon-144x144.png) shouldnt happen in the official setup provided here: http://www.larsformella.de/portfolio/programme-software/xg/download/

After you modified the settings.xml you have to restart XG, of course.

**Comment by hrvstr** [comment]
Ok, seems like i downloaded something else yesterday. I deleted all files and did a fresh install. everything is working as expected except that i cannot forward XG in the windows firewall thus i can only access the WebGUI from another computer when i disable the windows firewall :/

the problem with the settings.xml are fixed now, thanks!

**Comment by lformella** [comment]
Did you executed the commands listed here?
https://github.com/lformella/xdcc-grabscher#if-running-on-windows-vista-and-greater

**Comment by hrvstr** [comment]
Yes I did, and i just tried again and it told me "file could not be created, because it already exists". so it successfully created those files, but i still need to disable the firewall to get to the WebGUI from another computer.

**Comment by lformella** [comment]
Did you checked all boxes in the firewall dialog?
Just the one in the screenshot wont suffice.

![fw](https://f.cloud.github.com/assets/857226/611486/fd7fd7d8-cdd4-11e2-8100-e2a21a8c65e3.png)

**Comment by hrvstr** [comment]
I think I didn't get a firewall dialog, i added a rule manually. At first I added "Server.CMD.exe" to the firewall whitelist, which should allow all ports i think. That didn't work so i tried forwarding port 5556+5557 to my server IP via the advanced firewall settings, no luck either. the problem has to be the firewall, since it works when i disable it completely.

I will try to delete every XG-related entry from the firewall and see if I get a dialoge when launching the server.
thanks for the help, really appreciate your project!

**Comment by hrvstr** [comment]
I deleted every XG entry in the firewall and did a fresh start. I got the firewall dialog and checked all boxes. still no luck, i can only access it with the firewall disabled.i don't have any other software firewalls just the native win 8 firewall and microsoft security essentials. do i have to forward something in the router?

**Comment by hrvstr** [comment]
just wanted to say that the problem is still there. xg is running with admin rights, i checked all boxes and ran the 2 shell commands. is there anything left i can try? i don't really want to leave my firewall open all the time :/

**Comment by lformella** [comment]
Sorry mate, but i dont run windows (exept for gaming and at work), so i cant reproduce your issue nor help you. Did you tried googling your problem? It might be a firewall issue, because XG is working fine with linux / mono.

**Comment by hrvstr** [comment]
i am now running XG on a XBMCbuntu install on the same machine and I am having a much better experience. the web interface seems snappier than before, install was a breeze (just copy the files and launch the script via ssh) and i dont experience lags anymore when getting a lot of search results. 

so while i couldn't find a solution for the problem the issue is solved.
