### ISSUE TITLE
server list duplicates itself on opening server entry

### ISSUE THREAD

**Issue by Strubbl** [lformella/xdcc-grabscher#2]
if i open a server entry in the server list in the upper left (click on the small triangle left of the server entry label), the whole server lists inserts itself another time in the list. 
afterwards, i have a list in a list, so i can open an entry while opening an entry

my version: 
small size improvements
commit f1c2c0ca480f7af08eaef951422db94b31748927
lformella authored September 07, 2011

**Comment by lformella** [comment]
solved in 150ee294e117eb9462b0e2b6a7451a52eec35a44
