### ISSUE TITLE
Problems with connecting to specific channels

### ISSUE THREAD

**Issue by Simiil** [lformella/xdcc-grabscher#25]
Connecting to the Server `irc.scenep2p.net` works, and connecting to channels work. But if i connect to the channel `#the.source` it connects fine, gets the channel information and after a few seconds the whole server loses connection. The same happens with the server `irc.oceanirc.net` and the channel `#oce@n`

As soon i have some time i'll try to get more debug information

**Comment by borkie** [comment]
idem here if i connect to some server and try to join certain channels.
XG report
<code>FATAL [12] 0:XG.Server.Plugin.Core.Irc.IrcConnection(irc.openjoke.org).StartRun() connection failed
Could not connect to: irc.openjoke.org:6667 the value cannot be null
Parameter name: channelname</code>

**Comment by lformella** [comment]
please try XG 3.0.0.0 (https://github.com/lformella/xdcc-grabscher/releases/tag/v3.0.0.0)

if the problem is still there please post again :-)

**Comment by borkie** [comment]
Even with version 3.0.0.0 there is still the same problem.
You can see it by connecting  to irc.darksin.net and if you join #universal channel all is ok, but if you try to join #fusion or #atena XG disconnect from server

Reopen this issue :)

**Comment by lformella** [comment]
Oh, I see - its a problem with a 3rd party lib. (https://github.com/meebey/SmartIrc4net/pull/18)

**Comment by lformella** [comment]
I uploaded a fix here: https://github.com/lformella/xdcc-grabscher/releases/tag/v3.0.0.1

**Comment by borkie** [comment]
thank you so much!!
