### ISSUE TITLE
API/xdcc-link handling

### ISSUE THREAD

**Issue by Freedos** [lformella/xdcc-grabscher#26]
Hallo Lars!

I've been looking for years for good XDCC-client which can handle multi part downloads. Awesome!

It would be nice if if XG imports the packetinformation when you click xdcc-links (like xWeasel and ircklipper).

An API to use XG with Couchpotato or Sickbeard would also be a nice feature or at least a frequently scanned folder where you could drop txt files with xdcc-links.

hear is my usescript for xdcc.me and xdccfinder:

//##################################################
// ==UserScript==
// @name        XDCC Finder-XG
// @namespace   freedosjuinkmail@aol.com,2013-11-18:XDCCfindGrabscher
// @description Replaces irc-links with a popup containing a xdcc-link
// @include     http://www.xdccfinder.com/results.php*
// @include     http://www.xdcc.me/search.php*
// @version     1
// @grant       none
// ==/UserScript==

var links = document.getElementsByTagName("a");
for (i = 0; i < links.length; i++) { 

```
var node = links[i];
var link = node.getAttribute("href");
var title = node.getAttribute("title");
var command = node.getAttribute("onclick");
//#######################################################################
// reads information from irc link and title and pastes them in variables
if (link && link.indexOf("irc://") > -1) {
    var server = link.slice(4,link.lastIndexOf('/'));
    var servername = link.slice(link.indexOf('.')+1,link.lastIndexOf('.'));
    var channel = link.slice(link.lastIndexOf('/') + 1);
    var bot = title.slice(title.indexOf(' ')+1, title.lastIndexOf(' xdcc send'));
    var packetnumber = title.slice(title.indexOf('#')+1,title.lastIndexOf(' Control-V to paste.'));
    var filename = 'test.avi';
    var xdccLink = 'xdcc:'+ server +'/'+ servername +'/#'+ channel +'/'+ bot +'/#'+ packetnumber +'/'+ filename +'/';

    //#######################################################################
    //remove irc-links, replace with popup containing xdcc link 
    node.removeAttribute("href");
    //node.setAttribute("href", xdccLink);
    //node.setAttribute("title", bot);
    node.setAttribute("onclick","javascript:prompt('Control-C to copy, then enter', '"+xdccLink+"');");
}
```

}

//example XDCC-link: xdcc://irc.server.net/servername/#channel/bot/#3/Test.avi/
//###################################################################

**Comment by lformella** [comment]
Hi,

i dont know Couchpotato or Sickbeard - so how should an api look like?

Do you want to enable packets by calling urls? (like http://xg.de/packet/guid/enable ...)
Or just add xdcc links? (like http://xg.de/addLink?password=test&link=irc.server.de/#channel ...)

**Comment by Freedos** [comment]
If you don't know Sichkbeard and Couchpotato you should definitely take a look at them.
http://sickbeard.com/
https://couchpota.to/

I'm still writing the the searcher plugin for couchpotato using xdccFinder.
To add packets to xdcc grabscher, i believe the most usefull option would be adding xdcc links.
They've been used since irc klipper and countain the filename information.

Best Regards
Freedos

**Comment by lformella** [comment]
Solved in fc438f9 (https://github.com/lformella/xdcc-grabscher/blob/xg3/README.md#api)

**Comment by Freedos** [comment]
awesome

Mal gucken ob ich alter Maschi jetzt das plugin fertig krieg ;-)

**Comment by lformella** [comment]
Müssen das unbedingt GET Requests sein, oder kannst du auch JSON Objekte per POST übergeben?

Also statt

GET ht*p://your-own-host:5556/api/615d86bb-f867-47c1-a860-ac24e09e976c/parseXdccLink/irc.test.net/servername/channel/bot/1/filename/

POST ht*p://your-own-host:5556/api/parseXdccLink

``` json
{
"key": "615d86bb-f867-47c1-a860-ac24e09e976c",
"link": "irc.test.net/servername/channel/bot/1/filename/"
}
```

Letzteres würde mir besser gefallen.

**Comment by Freedos** [comment]
JSON ist super. Sorry das ich so lang nicht geantwortet habe. Was dir am besten passt

**Comment by Khundian** [comment]
Great you included this in your download client :+1:, but the exact format for the pack should be 4 digits. Thats the way its always been used before in other clients, would be so nice if you could do the same 
<code>
xdcc://irc.server.net/servername/#channel/bot/#0003/Test.avi/
xdcc://irc.server.net/servername/#channel/bot/#0030/Test.avi/
<code>

Thanks :)
