### ISSUE TITLE
Webfrontend keeps dropping connections

### ISSUE THREAD

**Issue by mmaedler** [lformella/xdcc-grabscher#28]
Hi, 

I'm using xg version 2.2.0.0 on a Ubuntu 12.04LTS Server and everytime I log in it takes a couple of seconds and the web frontend tells me "Verbindung zum XG Server verloren - bitte Seite neu laden!" and I need to relogin. The logfile is empty.

Also adding new servers is not possible as after hitting "Hinzufügen" nothing seems to be saved.

Any ideas? 

Thanks a mil,
Moritz

**Comment by lformella** [comment]
please try XG 3.0.0.0 (https://github.com/lformella/xdcc-grabscher/releases/tag/v3.0.0.0)

if the problem is still there please post again :-)
