### ISSUE TITLE
Can't start XG3 without start.sh.

### ISSUE THREAD

**Issue by hrvstr** [lformella/xdcc-grabscher#29]
I wanted to try out XG3 today but the zip file doesn't include a "start.sh" anymore. i tried to use the old one from V2.2 with the EXE-filename modified but without luck. I am getting:

```
Unhandled Exception: System.TypeInitializationException: An exception was thrown by the type initializer for XG.Config.Properties.Settings ---> System.TypeLoadException: Could not load type 'System.Runtime.CompilerServices.ExtensionAttribute' from assembly 'XG.Config'.
  --- End of inner exception stack trace ---
  at XG.Application.Programm.Main (System.String[] args) [0x00000] in <filename unknown>:0 
[ERROR] FATAL UNHANDLED EXCEPTION: System.TypeInitializationException: An exception was thrown by the type initializer for XG.Config.Properties.Settings ---> System.TypeLoadException: Could not load type 'System.Runtime.CompilerServices.ExtensionAttribute' from assembly 'XG.Config'.
  --- End of inner exception stack trace ---
  at XG.Application.Programm.Main (System.String[] args) [0x00000] in <filename unknown>:0 
```

I am using XBMCbuntu via ssh. I installed all the packets needed with the command from the tutorial.
I managed to get it working under Mac OSX with the modified start.sh that looks like this:

```
#!/bin/bash

SOURCE="${BASH_SOURCE[0]}"
DIR="$( dirname "$SOURCE" )"
while [ -h "$SOURCE" ]
do 
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE"
  DIR="$( cd -P "$( dirname "$SOURCE"  )" && pwd )"
done
DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"

cd $DIR
mono XG.Application.exe > log.txt & pid=$!
echo $pid > pid
```

when i try to run it with the mono command on Ubuntu

```
sudo mono XG.Application.exe
```

i am getting this:

```
Missing method .ctor in assembly /home/hrvstr/xg/XG.Plugin.Webserver.dll, type System.Runtime.CompilerServices.ExtensionAttribute
Can't find custom attr constructor image: /home/hrvstr/xg/XG.Plugin.Webserver.dll mtoken: 0x0a00019d
Missing method .ctor in assembly /home/hrvstr/xg/XG.Config.dll, type System.Runtime.CompilerServices.ExtensionAttribute
Can't find custom attr constructor image: /home/hrvstr/xg/XG.Config.dll mtoken: 0x0a000001

Unhandled Exception: System.TypeInitializationException: An exception was thrown by the type initializer for XG.Config.Properties.Settings ---> System.TypeLoadException: Could not load type 'System.Runtime.CompilerServices.ExtensionAttribute' from assembly 'XG.Config'.
  --- End of inner exception stack trace ---
  at XG.Application.Programm.Main (System.String[] args) [0x00000] in <filename unknown>:0 
[ERROR] FATAL UNHANDLED EXCEPTION: System.TypeInitializationException: An exception was thrown by the type initializer for XG.Config.Properties.Settings ---> System.TypeLoadException: Could not load type 'System.Runtime.CompilerServices.ExtensionAttribute' from assembly 'XG.Config'.
  --- End of inner exception stack trace ---
  at XG.Application.Programm.Main (System.String[] args) [0x00000] in <filename unknown>:0 
```

**Comment by Simiil** [comment]
same here, using Linux Mint and `Mono JIT compiler version 2.10.8.1 (Debian 2.10.8.1-5ubuntu1)`

**Comment by lformella** [comment]
I 'll update the zip file today in the evening, but as i mentioned here (https://github.com/lformella/xdcc-grabscher#on-linux-with-mono) you need mono 3.x

**Comment by hrvstr** [comment]
I am having a really hard time installing mono 3 on my 32bit XBMCbuntu 12.10 box. I added `deb http://debian.meebey.net/experimental/mono /` to my `/etc/apt/sources.list` file and tried to install with this command `apt-get install mono-complete`. When I try to dist-upgrade the mono dependencies keep getting kept back with this error message `E: Some packages could not be authenticated``

**Comment by lformella** [comment]
I updated the files and added a new stop.sh

**Comment by lformella** [comment]
I used the same sources and was asked if I want to really install from unauthenticates sources - typed y and it worked.

**Comment by hrvstr** [comment]
Thanks for adding the start.sh and giving help with mono. I still didn't get it to work and I think I may be out of luck at the moment. I will probably wait for Mono3 to be supported in my Ubuntu distro. I downgraded to XG 2.2. for the moment. I will try to set it up when I find some free time and report back!
