### ISSUE TITLE
Client crash & password error

### ISSUE THREAD

**Issue by Shaaah** [lformella/xdcc-grabscher#3]
When I try starting the client it just crashes (got no idea why).
When I try to use the webserver, I get a error saying my nickserv password is wrong (on the sever window). I filled my password in the <IrcRegisterPasswort> settings.xml file, but i wonder if it works.

**Comment by lformella** [comment]
Great, that you find your way here and filled out a bug report :)

But, you have attach a few things to this and future bug reports:
1. Which version of XG are you using? Did you downloaded it from github, sourceforge or elsewhere? Or did you maybe compiled it your own? If so, which commit are you using?
2. Which OS and version of .Net / Mono are you using? Windows XP, Ubuntu, ...?
3. Where and when did the error message appear? It is easier if you copy the whole text from the log file, or attach it to your post. But make sure, to not include private data!

Doing so, its easier for me to analyse yout problem and fix it! :)

**Comment by lformella** [comment]
I have to mention, that the gtk client might be broken, because i didn't use it anymore. Therefor i already dropped it of the repository. All future versions of XG only will include the webserver, because it is much easier to manage.

Also the nickserv functions are not working at the moment. You can add your credentials, but it wont work properly. It is a point on my todo list, after including the search results of xg.bitpir.at directly into the webserver.

**Comment by Shaaah** [comment]
Thanks for the answer!
I've been using the XG server installer I got from the website (http://www.larsformella.de : 0.8) on Windows 7. And I'm runnning on .NET 4.0.3.
The problem with the gtk client isn't that important because I can use the webclient. But all of the xdcc download I'm interested into are on nickserv protected channels so, I'll be trying the soft when the update will come out!

**Comment by sysmike** [comment]
You could make a separate repository for the GTK Client, so I can fork it and try to get it working again. I really liked the server-client concept you were working on.

**Comment by lformella** [comment]
You dont like the frontend of the webserver? I like it much more than the gtk stuff. It runs with every browser and doesnt depend on installed gtk libs.

You can already fork the project now and do a rollback to r150ee294e1, before i was dropping the tcp support including the client. There you will find a winforms client (XG.Client.TCP.WinForms), too. It is just a basic fork of the gtk stuff, but should be a good starting point if you are using windows.
If you are making some usefull improvements, i will re-add tcp support and add your new stuff, of course. :-)

**Comment by lformella** [comment]
this is the commit (r150ee294e1) you should rollback to: https://github.com/lformella/xdcc-grabscher/tree/150ee294e117eb9462b0e2b6a7451a52eec35a44

**Comment by sysmike** [comment]
Thanks for the hint, will start working on it the next day.

I prefer a more or less native gui over a webfrontend, at home I have a nice gui and when I am not at home I have the webfronted.

**Comment by Shaaah** [comment]
Hi!
I saw that the nickserv should work now, and I tried to build (with visual C# 2010 express) and failed :D
Can you tell me what I should build with?

**Comment by lformella** [comment]
A new release (0.9) is planed at the end of the week. It will include all recend changes and hopefully is stable enough to release the version 1.0 soon.

**Comment by lformella** [comment]
Here it is: https://github.com/lformella/xdcc-grabscher/downloads

**Comment by Shaaah** [comment]
Thanks!
I think you made a typo and swapped the names of the Linux & Windows versions.

**Comment by Shaaah** [comment]
I've got two questions : How do you download a pack from a bot I cant see in the bot list? And how do I check if I am connected to a channel?

**Comment by lformella** [comment]
I changed the files and will upload a new linux archive tonight - the file i uploaded yesterday was broken :-|

To download a file you have to search for packets. You can do this on the "xg.bitpir.at" tab and use the great external search, or on the internal tab. Therefore you have to add servers and channels manually with the "server / channels" button on the top. If you search packets with the external search the specific server and channel will be added automatically, so this might be the faster and easier choice.
