### ISSUE TITLE
A lot of missing file

### ISSUE THREAD

**Issue by borkie** [lformella/xdcc-grabscher#30]
If i try to install XG 3.0.0.0 msi under Windows 7 64bit professional a lot of file missing (return error 1308, source file missing).
Else if i try to load XG.Application.exe from the zip archive i get:
<code>Unhandled Exception: System.IO.FileNotFoundException: Unable to load the file or the assembly 'Mono.Posix, Version=4.0.0.0, Culture=neutral, PublicKeyToken=
0738eb9f132ed756' or one of its dependencies. Unable to find the file specified. at XG.Application.Programm.Main(String[] args)</code>

**Comment by lformella** [comment]
Ups, I forgot to label the downloads correctly.

The zip file is for Linux / Mac only. You should use the provided msi file.

**Comment by borkie** [comment]
If i try to install the msi i've a lot of error (missing files) like this:
<code>Error 1309.
Error reading from file: C:\Users\username\Desktop\program files\XG\XG.Application.exe.
Verify that the file exists and that you can access it.</code>
if i ignore it i've the same error for XG.Application.exe.config, agsXMPP.dll, HtmlAgilityPack.dll, Iesi.Collections.dll, log4net.dll, Meeby.SmartIrc4net.dll, Microsoft.AspNet.SignalR.Core.dll, Microsoft.CSharp.dll, Microsoft.Owin.dll, Microsoft.Owin.Hosting.dll and a lot of other file!

**Comment by lformella** [comment]
Please try the provided XG_3.0.0.0.exe file - this one should work.

**Comment by borkie** [comment]
Thank you, now XG starts!
