### ISSUE TITLE
No notifications description

### ISSUE THREAD

**Issue by borkie** [lformella/xdcc-grabscher#32]
Under Windows 7 there aren't any description but only generic "Notification_Description_11" messages, it seems that some {{}} are missing around variable name, right?

<img src="http://imageshack.com/a/img13/1527/hzkl.jpg"/>

**Comment by lformella** [comment]
I translated the messages into German and if you do not have a German locale, the English one should be used. Should... ;-)

I uploaded a fix here: https://github.com/lformella/xdcc-grabscher/releases/tag/v3.0.0.1
