### ISSUE TITLE
XG 3.0.0.1 crashes on startup (Windows)

### ISSUE THREAD

**Issue by copen2** [lformella/xdcc-grabscher#34]
I deinstalled XG 2.3, then installed XG 3.0.0.1.  It crashes on startup every time.  

![capture](https://f.cloud.github.com/assets/6564256/2059033/d75b0588-8b92-11e3-9f5b-ddb6b5bcc300.PNG)

**Comment by lformella** [comment]
please try the new release: https://github.com/lformella/xdcc-grabscher/releases/tag/v3.1.0.0

**Comment by copen2** [comment]
![crash](https://cloud.githubusercontent.com/assets/6564256/2750946/db73c888-c8a7-11e3-86f5-a125785a1b26.png)
Sorry, didn't have time to get back to this until now.

Still crashes on 3.1.0.1 upon launch.  Very frustrating.  Does this have something to do with the fact that I used to have 2.3 installed?
