### ISSUE TITLE
Error in Web-Interface (on Mono)

### ISSUE THREAD

**Issue by kahoona77** [lformella/xdcc-grabscher#35]
Hi,

I'm getting the following error, when i try to start the XG-Web-Interface:

(This is the log is from the chrome-console):

```
GET http://192.168.66.11:5556/signalr/hubs?noext= 500 (Internal Server Error) require.js:1895
Uncaught Error: Script error for: signalr.hubs http://requirejs.org/docs/errors.html#scripterror require.js:166
Uncaught Error: Load timeout for modules: angular,ipCookies,ngAnimate,ngSanitize,ngTable,ui.bootstrap,ngTranslate
http://requirejs.org/docs/errors.html#timeout require.js:166
```

XG is running on Mint-Linux with Mono (v3.2.1).
I also had to copy "System.Xml.Linq.dll" to the XG-directory to get it started. Maybe this is the problem.

Im very excited about your software. i was searching for something like this for some time now.

**Comment by lformella** [comment]
Was XG writing an error in the console / log, too? If you could post it or send via email it would be great! :)

**Comment by lformella** [comment]
If you are running ubuntu, take a look here: #39

**Comment by scottc** [comment]
I would advice against copying any System.*.dll to XG directory if possible, these are the .net framework dlls, and would typically be installed globally on your machine. Instead I would make sure I had the latest .net framework or mono installed correctly.

Also keep in mind there are various versions of the .net framework, so if you were to copy that dll you would also need to make sure you grab the correct dll version. As you can have multiple versions installed on your machine.
