### ISSUE TITLE
Can't start XG 3.1.0.1 on Ubuntu 14.04

### ISSUE THREAD

**Issue by Freedos** [lformella/xdcc-grabscher#39]
When i start "mono XG.Application.exe" with XG 3.1.0.1 nothing happens.
I can open XG in browser but the Page is empty except the title "XG Webfrontend v{{VERSION}}". I don't get any errors over ssh.
2.2 has been working great. My mono version is: "Debian 3.2.8+dfsg-4ubuntu1".

Probably it's mono but I don't know how to switch back to a more stable Version.
Thanks for any help.

**Comment by lformella** [comment]
Could you enable the browser "debug mode" using firebug in firefox or developer tools in chrome / ie? Maybe there are some javascript errors which will stop the creating of the webgui.

**Comment by Freedos** [comment]
Thats what I get with Firebug:

Error: Load timeout for modules: angular,ipCookies,ngAnimate,ngSanitize,ngTable,ui.bootstrap,ngTranslate
http://requirejs.org/docs/errors.html#timeout
http://192.168.1.101:5556/Scripts/require.js
Line 166

**Comment by lformella** [comment]
Please try reloading your browser with F5. I experienced the problem some time ago and solved it by reloading the page. Maybe you must reload it multiple times. I will look into the issue, but this might solve your problem.

**Comment by lformella** [comment]
If it wont work, please try the solution mentioned in issue #35

**Comment by Freedos** [comment]
Okay I tried to put System.Xml.Linq.dll in XG folder acording to #35.
This resulted in an uhandled expection:
http://pastebin.com/i7ZhDcRW

Refreshing didn't really worked out for me

**Comment by lformella** [comment]
"Address already in use" means some process already uses the port of the build in webserver. Either a XG process is still running, or another 3rd party application uses this port. Please kill XG if its running or choose another port if it conflicts with other applications.

**Comment by Freedos** [comment]
Ah sorry for that. tried again and got same results as before. Refreshing didn't help.

**Comment by lformella** [comment]
I guess it is related to #55

**Comment by lformella** [comment]
Please try installing "mono-complete". I tried a a fresh 14.04 ubuntu box today and there were some mono libs missing. I could not find out which one exactly, but pulling all in did the trick.

**Comment by scottc** [comment]
I would advice against copying any System.*.dll to XG directory if possible, these are the .net framework dlls, and would typically be installed globally on your machine. Instead I would make sure I had the latest .net framework or mono installed correctly.

Also keep in mind there are various versions of the .net framework, so if you were to copy that dll you would also need to make sure you grab the correct dll version. As you can have multiple versions installed on your machine.

**Comment by lformella** [comment]
solved in #55
