### ISSUE TITLE
make "Updated" column in external search sortable

### ISSUE THREAD

**Issue by Strubbl** [lformella/xdcc-grabscher#4]
Yeah, I know I can already sort the results from the external search, but please don't make the dates in the column "Aktualisiert/Updated" look like "Friday at 08:26" and "20. May at 10:26". Because of that mixture the sorting of the strings is not in the right logical date order. So the results aren't sorted in the correct time order.

**Comment by lformella** [comment]
The sorting happens on the server, even using external search. Jqgrid depends on this workflow and this is much more faster then receiving the whole list and sorting it on the client. The displayed strings are just different formats of the timestamps received from the server.
