### ISSUE TITLE
shutdown XG via GUI

### ISSUE THREAD

**Issue by Strubbl** [lformella/xdcc-grabscher#40]
Is it possible to add a feature, where one can shutdown XG via the web interface? Maybe a menu item can be added to the options menu? (And perhaps an "are you sure to shutdown" popup before really shutting down.)

**Comment by hrvstr** [comment]
This already exists since v3 minus the confirm dialogue.

Am Freitag, 4. April 2014 schrieb Strubbl :

**Comment by Strubbl** [comment]
OMG, I overlooked that. Sorry!
