### ISSUE TITLE
Item name clean-up when xdcc listing

### ISSUE THREAD

**Issue by Khundian** [lformella/xdcc-grabscher#43]
When xdcc listing bots, XG puts the date and time of when the packet was uploaded in the item name in the search results. Looks kinda messy, would be nice if you could remove the date and time from the item name.

Thanks!

**Comment by lformella** [comment]
Can you please take a screenshot and describe exactly what you mean?

**Comment by Khundian** [comment]
Hi Lars,

I tried to replicate this issue, but strangely I cannot do it again. XG keeps asking the next bot for version, and never asks a bot for a list now.

But I think I got this issue because I was listing modified iroffer bots. Many servers/channels use their own modifield version, maybe XG gets confused with the custom output it gets from these modified bots. I cannot code myself, but I took a look in your source files and noticed you used the XDCC HELP command. I assume XG uses the output of the XDCC HELP to determine what it should do next. Download the list as a text file, or send the XDCC LIST command to the bot, etc. I can imagine if XG doesn't see the output it expects to see, it doesn't work or maybe act weird.

output examples of XDCC HELP command:

<code>
-XXBOTNAME- *\* Per richiedere la lista:    "/MSG XXBOTNAME XDCC LIST" **
-XXBOTNAME- *\* Per richiedere lo stop del Listing: "/MSG XXBOTNAME XDCC STOP" **
-XXBOTNAME- *\* Per effettuare una ricerca:       "/MSG XXBOTNAME XDCC SEARCH pattern" **
-XXBOTNAME- *\* Per richiedere un file: "/MSG XXBOTNAME XDCC SEND pack" **
-XXBOTNAME- *\* Per mostrare il tempo di attesa: "/MSG XXBOTNAME XDCC QUEUE" **
-XXBOTNAME- *\* Per richiedere la rimozione dalla coda: "/MSG XXBOTNAME XDCC REMOVE" **
-XXBOTNAME- *\* Per cancellare il download: "/MSG XXBOTNAME XDCC CANCEL" **
</code>

<code>
-XXBOTNAME- *\* Per Richiedere La Lista:    "/MSG XXBOTNAME XDCC LIST" **
-XXBOTNAME- *\* Per Richiedere Lo Stop Della Lista: "/MSG XXBOTNAME XDCC STOP" **
-XXBOTNAME- *\* Download batch:    "/MSG XXBOTNAME XDCC BATCH group" **
-XXBOTNAME- *\* Per Fare Una Ricerca:       "/MSG XXBOTNAME XDCC SEARCH pattern" **
-XXBOTNAME- *\* Per Richiedere i Dettagli:  "/MSG XXBOTNAME XDCC INFO pack" **
-XXBOTNAME- *\* Per Richiedere Un Download: "/MSG XXBOTNAME XDCC SEND pack" **
-XXBOTNAME- *\* Per Mostrare il Tempo da Attendere: "/MSG XXBOTNAME XDCC QUEUE" **
-XXBOTNAME- *\* Per Richiedere la Rimozione Dalla Coda: "/MSG XXBOTNAME XDCC REMOVE" **
-XXBOTNAME- *\* Per Cancellare il Download: "/MSG XXBOTNAME XDCC CANCEL" **
</code>

If what I think is right, maybe it would be better to simplify the routine to a "version check", "MSG XXBOTNAME XDCC LIST" command and a user configable timer when to check the next bot in XG options or something like that.

As a matter of fact, I'll leave that up to you, you've done a brilliant job already!

Thanks

**Comment by lformella** [comment]
Can you please name the server and channel where you noticed this behaviour? You can send an email if you don't want to write it down in public.

XG will just asked voiced users to reply the version. I implemented this restriction because it is a bad practise to ask all users in a channel. Some clients alert the user on a ctcp version request and this is mostly detected as spam. I had a long discussion with some users when i developed this feature and tested it in their channel without voice restriction.

**Comment by Khundian** [comment]
I sent you a mail :)

**Comment by lformella** [comment]
I have been in one of your channels for two hours and XG was getting a bunch of packets and was not kicked because of ctcp spam :-)

**Comment by Khundian** [comment]
Indeed, its working nicely, You work fast :)
Thanks!
