### ISSUE TITLE
Download automatically a xdcc link at XG startup

### ISSUE THREAD

**Issue by antoine-morisseau** [lformella/xdcc-grabscher#45]
Hello,

I found an issue that occure quite often when i try to cancel a download in progress.
If after cancelled the download i shutdown XG and restart it at connecting to the ircs servers and channel it re send an xdcc send request and download automatically the cancelled file.

It is hard for me to get any trace since i don't know how to put the console log into a file and copy past here.

**Comment by lformella** [comment]
Do you cancel the downloads in the file view? ATM there is a bug in this view which will delete the files, but don't disable the packets - so they are requested again upon restart. If you cancel the downloads in the packet / bot view this issue should not happen.

**Comment by antoine-morisseau** [comment]
Okay but the thing is i ask the packet with the xdcc link inputs (for the xdcc bot i use the xdcc bot listing etc doesn't work) so they doesn't appear in any other view. it appear only in the download view.
But thanks for the issue solved !
