### ISSUE TITLE
Feature Request: Allow downloading via right click

### ISSUE THREAD

**Issue by Schabernack** [lformella/xdcc-grabscher#5]
Currently you have to doubleclick on a packet to start downloading. This seems to be a bit unreliable from times to times and the packets aren't added correctly to the enabled packet section. A right click context menu with which you can start the download would solve this issue and would also make it clearer if the packet has been added to your download list.

another advantage of this would be, that you could select multiple packets which are then downloaded.

**Comment by lformella** [comment]
Since https://github.com/lformella/xdcc-grabscher/commit/fe80aadaa975996830885b332ebe4f04d286aaf5 you can click on the small icons to disable / enable the current object :-)
