### ISSUE TITLE
API url Encoding

### ISSUE THREAD

**Issue by Freedos** [lformella/xdcc-grabscher#59]
Hey,

I think I've found a bug in the api. When the link contains special characters like "[MG]-TV|EU|S|Brothers" i get a blank website as response. The problem seems to be the "|" character. Also encoding "|" to %7C didn't work. Would be nice if you can fix this.

**Comment by lformella** [comment]
Fixed in [v3.3.0.0](https://github.com/lformella/xdcc-grabscher/releases/tag/v3.3.0.0)
