### ISSUE TITLE
Not Start on Windows 7

### ISSUE THREAD

**Issue by Thunder88** [lformella/xdcc-grabscher#6]
I have downladed from here:
https://github.com/lformella/xdcc-grabscher/downloads

This:
XG_Server_0.9.1.msi— XG 0.9.1 Windows Installer
XG_Client_0.8.msi— XG Client 0.8 Windows Installer

My system is Windows 7 x64.

If i open the client simply crash:
APPCRASH Bucket  42039787, Type 4
P1: XG.Client.TCP.GTK.exe
P2: 0.8.0.0
P3: 4d8360cd
P4: KERNELBASE.dll
P5: 6.1.7601.17651
P6: 4e21213c
P7: e0434f4d
P8: 000000000000cacd
P9: 
P10: 

If i open the server:
http://i.imgur.com/gsiMu.jpg

If i install both 0.8 version:
XG_Server_0.8.msi— XG 0.8 Windows Installer
XG_Client_0.8.msi— XG Client 0.8 Windows Installer

The client doesn't start like before, the client give me error:
Could not file setting.xml - ACCESS VIOLATED
Many other .xml files

But that files are in the folder...

Anyway, seems a cool software, hope i can use one day,
Good work

**Comment by Strubbl** [comment]
The problem you might have is a typo. Control if you have a file "setting.xml" or "settings.xml". There was a bug with the missing "s" if i remember it correctly.

I think the GTK client is not supported anymore. Use the web interface after starting the server by browsing to http://localhost:5555/ (or whatever you have configured)

**Comment by lformella** [comment]
Yes - please dont use the GTK client. The webserver will fit all your needs.

Which port did you specified before starting the 0.9.1 server? And what means "accesso negato" in english? It seems that the port is already taken or you dont have enough rights to open a port. Do you use a firewall or a similar product which is blocking xg?

**Comment by Thunder88** [comment]
So i need to use only:
XG_Server_0.9.1.msi
Right?

I'll check it out for the "s" very soon. I don't have any external firewall, i don't have set nothing...

I have:
1) Installed server
2) Start the server from link on desktop
3) Error

Accesso Negato mean access denied.
Thanks for support

**Comment by Thunder88** [comment]
UPDATE:
Start XG Server 0.9.1 on a VM with Windws 7 SP1, the errors are:

10-10-2012 08:13:40,778 FATAL [ 1] Settings.Instance (Settings:0)
System.IO.FileNotFoundException: Could not find file 'C:\Program Files (x86)\XG\
XG Server\settings.xml'.
File name: 'C:\Program Files (x86)\XG\XG Server\settings.xml'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, I
nt32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions o
ptions, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolea
n useLongPath)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access,
FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean
bFromProxy)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access,
FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detec
tEncodingFromByteOrderMarks, Int32 bufferSize)
   at System.IO.StreamReader..ctor(String path, Boolean detectEncodingFromByteOr
derMarks)
   at XG.Server.Settings.Deserialize()
10-10-2012 08:14:45,195 FATAL [ 3] Settings.Instance.Deserialize()  (Statistic:0
)
System.IO.FileNotFoundException: Could not find file 'C:\Program Files (x86)\XG\
XG Server\statistics.xml'.
File name: 'C:\Program Files (x86)\XG\XG Server\statistics.xml'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, I
nt32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions o
ptions, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolea
n useLongPath)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access,
FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean
bFromProxy)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access,
FileShare share)
   at XG.Server.Statistic.Deserialize()

But i have settingS and statisticS in the folder on the software.
I have try to run XG in admin mode, nothing
I have try to run in conmpatibility mode XP SP3, i see the CMD windows of XG Server without error, but nothing else. I'm missing something?

**Comment by Strubbl** [comment]
Hmm, I cannot reproduce the error. I installed it and .net 4.5. If I start the XG server via Admin command prompt, there is no problem:

```
C:\Windows\system32>cd C:\Program Files (x86)\XG\XG Server

C:\Program Files (x86)\XG\XG Server>XG.Server.Cmd.exe
```

Okay, after a while he complains about not having a statistics.xml, but that shouldn't be a problem cause he creates it:

```
10-10-2012 10:08:26,152 FATAL [ 3] Settings.Instance.Deserialize()  (Statistic:0)
System.IO.FileNotFoundException: Could not find file 'C:\Program Files (x86)\XG\XG Server\statistics
.xml'.
File name: 'C:\Program Files (x86)\XG\XG Server\statistics.xml'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean
 useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, St
ring msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int
32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at XG.Server.Statistic.Deserialize()
```

How do you start your XG server? Double click in your explorer? Run as admin? Via command line?

**Comment by Thunder88** [comment]
I have alredy wrote it, i have try both command line, the .exe in the main folder and admin mode.
Only with SP3 compatibility i can't see errors, but only a blank cmd of the server.
After that what i need to do? How to start the xdcc-grabsher gui?

**Comment by Strubbl** [comment]
The "blank cmd of the server" might be the good sign. Just start your browser and go to http://localhost:5556 or what you have configured in your settings.xml. The GUI is a website in your browser at the given address.

**Comment by Thunder88** [comment]
Ok, on Windows 7 64-Bit work only if:
Run with compatibility mode to XP SP3
Run as admin

Thanks for support, I think it's a problem with file permissions and work only with SP3 compatibility and run as Admin

Cool, now i see the WebGUI:
http://i45.tinypic.com/2iw8umq.jpg

Now how to add server and bot?
Example
irc.test.net
#testchannel
BOT-Name

**Comment by Strubbl** [comment]
just use Firefox. internet explorer sucks.

**Comment by lformella** [comment]
I will update the help section today, so you can easily add servers and channels by following the instructions steps.
