### ISSUE TITLE
Closing Connection: Connection Lost w<0

### ISSUE THREAD

**Issue by mmaedler** [lformella/xdcc-grabscher#62]
Hiya,

I am able to download again, but after a few bytes (random number) the download stops and the bot reports:
`Received: 17631 kb - Closing Connection: Connection Lost w<0 (Connection reset by peer)`

XDCC Grabscher sits behind a NAT firewall, so I was wondering if I need to open any other ports apart from the one for the webinterface?

Thanks,
m

**Comment by lformella** [comment]
The firewall should not be the problem. I am running XG behind a NAT FW, too. Is there some log output matching the bot or file?

**Comment by mmaedler** [comment]
Mhh — there's some log data, but I can see an obvoius relation to a bot/file: https://gist.github.com/04b0f9320028cca5926b

**Comment by lformella** [comment]
Fixed in [v3.3.0.0](https://github.com/lformella/xdcc-grabscher/releases/tag/v3.3.0.0)
