### ISSUE TITLE
cannot start on ubuntu 14.04

### ISSUE THREAD

**Issue by gopal-srinivas** [lformella/xdcc-grabscher#65]
getting this error , while running start.sh

Cannot open assembly 'XG.Application.exe': No such file or directory.

**Comment by lformella** [comment]
You can always run XG with mono if you are in the XG directory:
Normal:

> mono XG.Application.exe

Background:

> mono XG.Application.exe > log.txt &

**Comment by lformella** [comment]
Fixed in [v3.3.0.0](https://github.com/lformella/xdcc-grabscher/releases/tag/v3.3.0.0)
