### ISSUE TITLE
connecting via bouncer

### ISSUE THREAD

**Issue by Jaglag** [lformella/xdcc-grabscher#66]
Hi,
I want to connect into my bouncer where the networks and channels saved.
When i connect via serverip:Port:Password he always say hes connected but dont join any channel i say he should be in in network config.
And he spamming me over and over again with server connected message.
Is there a way for me to connect him to my bouncer?

**Comment by Jaglag** [comment]
in irc i can connect to my bouncer via /server ip:port username/networkname:password i dont get it to working via xg -.-

**Comment by lformella** [comment]
Bouncers and DCC loading through bouncers are not tested with XG. Because I dont have a bouncer nor the time to set it up and test the connections and I cant support this feature.

**Comment by Jaglag** [comment]
if you want i can give you an znc account from my own znc for testing.
znc is very easy to work with.

**Comment by lformella** [comment]
I am sorry, but I just can support / implement features I use myself or features which are not that complex. I dont even know if smartirc4net (the irc lib used by XG) supports bouncers.

**Comment by hashworks** [comment]
Yup, smartirc4net supports bouncers. I think ZNC acts just like any other IRC Server - what would I need to change to set a password for a server? I have the feeling it would work just fine.
