### ISSUE TITLE
Queue

### ISSUE THREAD

**Issue by andre4nap** [lformella/xdcc-grabscher#70]
Is possible to show a Queue list?
Thank you

**Comment by lformella** [comment]
What do you mean?

**Comment by andre4nap** [comment]
If I add some pack from same bot, the app don't enable simultaneous download. So if you can create a list of the queue packs would be wonderful, better if we can delete packs from queue

**Comment by lformella** [comment]
Do you know channels / bots where you can load more than one packet at once?

XG already has an internal queue. If you enable more than one packet from one bot, the packets will be requested one after another if the previous is completely downloaded. The packets which are enabled or are currently downloading can be displayed if you use a predefined search. If you disable packets, they will be removed from the internal queue, of course.

**Comment by andre4nap** [comment]
If i search for "-Downloads" I would get a list of downloaded files, right? I retrieve this message from server: "Lost connection to XG server - please reload page." Run on Debian 7.5 with Mono complete 3.10.0. There will be a fix for this issue?

**Comment by lformella** [comment]
Nope - if you want to search for downloads or enabled packets, you have to click on a predefined search. The text "downloads" is displayed in the search box, but this is just a visual clue. If you enter "downloads" manually, you will search for packets named "downloads".

**Comment by andre4nap** [comment]
I've tried on Windows 8.1 system and it work properly. On Debian 7.5 this feature don't work :(

**Comment by lformella** [comment]
Take a look at the new version [v3.3.0.0](https://github.com/lformella/xdcc-grabscher/releases/tag/v3.3.0.0) - it works on Win7 and OSX 10.10 using mono 3.10
