### ISSUE TITLE
Rss dcc downloader

### ISSUE THREAD

**Issue by Jaglag** [lformella/xdcc-grabscher#79]
Hi

a plugin/feature like this: https://github.com/ascent12/RSSDCC-bot
would be nice as source you can take xrel rss or a simmiliar site to download these episodes then.

**Comment by Freedos** [comment]
see #52

**Comment by lformella** [comment]
I dont have the time to write such special plugins, but you can do it yourself :-)

You can use the [Add command of the XG API](https://github.com/lformella/xdcc-grabscher#add) to add packets. You just have to write a small script / app / whatever, which reads a rss source and pipes the packets to XG.
