### ISSUE TITLE
Unbehandelte Ausnahme: System.ArgumentOutOfRangeException: startIndex darf nicht  länger als die Länge der Zeichenfolge sein.

### ISSUE THREAD

**Issue by pooks0r** [lformella/xdcc-grabscher#80]
This error gets thrown several times a day and kills the process

Unbehandelte Ausnahme: System.ArgumentOutOfRangeException: startIndex darf nicht
 länger als die Länge der Zeichenfolge sein.
Parametername: startIndex
   bei System.String.Substring(Int32 startIndex, Int32 length)
   bei Meebey.SmartIrc4net.IrcConnection._SimpleParser(Object sender, ReadLineEv
entArgs args)
   bei Meebey.SmartIrc4net.ReadLineEventHandler.Invoke(Object sender, ReadLineEv
entArgs e)
   bei Meebey.SmartIrc4net.IrcConnection.ReadLine(Boolean blocking)
   bei Meebey.SmartIrc4net.IrcConnection.Listen(Boolean blocking)
   bei Meebey.SmartIrc4net.IrcConnection.Listen()
   bei XG.Plugin.Irc.XdccClient.Connect() in c:\Users\Lars\Documents\GitHub\xdcc
-grabscher\XG.Plugin.Irc\XdccClient.cs:Zeile 716.
   bei XG.Plugin.Irc.IrcConnection.StartRun() in c:\Users\Lars\Documents\GitHub\
xdcc-grabscher\XG.Plugin.Irc\IrcConnection.cs:Zeile 398.
   bei System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   bei System.Threading.ExecutionContext.RunInternal(ExecutionContext executionC
ontext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   bei System.Threading.ExecutionContext.Run(ExecutionContext executionContext,
ContextCallback callback, Object state, Boolean preserveSyncCtx)
   bei System.Threading.ExecutionContext.Run(ExecutionContext executionContext,
ContextCallback callback, Object state)
   bei System.Threading.ThreadHelper.ThreadStart()

**Comment by lformella** [comment]
duplicate of #74
