### ISSUE TITLE
SignalR exception thrown by Task: System.Aggrega teException: Mindestens ein Fehler ist aufgetreten. ---> System.NotImplementedEx ception: Die Methode oder der Vorgang ist nicht implementiert.

### ISSUE THREAD

**Issue by pooks0r** [lformella/xdcc-grabscher#81]
this error gets thrown but won't kill the process

XG.Application.exe Warning: 0 : SignalR exception thrown by Task: System.Aggrega
teException: Mindestens ein Fehler ist aufgetreten. ---> System.NotImplementedEx
ception: Die Methode oder der Vorgang ist nicht implementiert.
   bei Microsoft.AspNet.SignalR.Owin.OwinWebSocketHandler.OwinWebSocket.get_Stat
e()
   bei Microsoft.AspNet.SignalR.WebSockets.WebSocketHandler.SendAsync(ArraySegme
nt`1 message, WebSocketMessageType messageType, Boolean endOfMessage)
   bei Microsoft.AspNet.SignalR.WebSockets.DefaultWebSocketHandler.Flush()
   bei Microsoft.AspNet.SignalR.Transports.WebSocketTransport.<PerformSend>d__8.
MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausge
löst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNo
tification(Task task)
   bei Microsoft.AspNet.SignalR.Transports.WebSocketTransport.<PerformSend>d__8.
MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausge
löst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNo
tification(Task task)
   bei Microsoft.AspNet.SignalR.Messaging.Subscription.<Invoke>d__2.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausge
löst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNo
tification(Task task)
   bei Microsoft.AspNet.SignalR.Messaging.Subscription.<Work>d__8.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausge
löst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNo
tification(Task task)
   bei Microsoft.AspNet.SignalR.Messaging.MessageBroker.<DoWork>d__2.MoveNext()
   --- Ende der internen Ausnahmestapelüberwachung ---
---> (Interne Ausnahme #0) System.NotImplementedException: Die Methode oder der
Vorgang ist nicht implementiert.
   bei Microsoft.AspNet.SignalR.Owin.OwinWebSocketHandler.OwinWebSocket.get_Stat
e()
   bei Microsoft.AspNet.SignalR.WebSockets.WebSocketHandler.SendAsync(ArraySegme
nt`1 message, WebSocketMessageType messageType, Boolean endOfMessage)
   bei Microsoft.AspNet.SignalR.WebSockets.DefaultWebSocketHandler.Flush()
   bei Microsoft.AspNet.SignalR.Transports.WebSocketTransport.<PerformSend>d__8.
MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausge
löst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNo
tification(Task task)
   bei Microsoft.AspNet.SignalR.Transports.WebSocketTransport.<PerformSend>d__8.
MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausge
löst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNo
tification(Task task)
   bei Microsoft.AspNet.SignalR.Messaging.Subscription.<Invoke>d__2.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausge
löst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNo
tification(Task task)
   bei Microsoft.AspNet.SignalR.Messaging.Subscription.<Work>d__8.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausge
löst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNo
tification(Task task)
   bei Microsoft.AspNet.SignalR.Messaging.MessageBroker.<DoWork>d__2.MoveNext()<
---
                                                                           .WebSockets.DefaultWebSocketHandler.Flush()         bei Microsoft.AspNet.SignalR.Transports.WebSocketTransport.<PerformSend>d__8.MoveNext()                                                                      --- Ende der Stapelberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgel”st wurde ---        

**Comment by lformella** [comment]
duplicate of #54
