### ISSUE TITLE
Add auto extract?

### ISSUE THREAD

**Issue by pnill** [lformella/xdcc-grabscher#88]
Wondering if you'd ever plan on adding an auto extract to the system to automatically extract any .tar files and any .rar/.r00 etc files that are produced after that.

There's tons of stuff written for torrents and usenet for it already.

**Comment by Strubbl** [comment]
this is already implemented. have a look at the file handlers: https://github.com/lformella/xdcc-grabscher#filehandlers

**Comment by pnill** [comment]
Ahh, seems the screenshots are missing so the file settings are unclear... can you possibly provide your file settings for it?

**Comment by Strubbl** [comment]
```
  <setting name="FileHandlers" serializeAs="String">
    <value>[{"Regex":".*\\.tar","Process":{"Command":"mkdir","Arguments":"%FOLDER%/%FILENAME%","Next":{"Command":"tar","Arguments":"xf %PATH% -C %FOLDER%/%FILENAME%","Next":null}}},{"Regex":".*\\.rar","Process":{"Command":"mkdir","Arguments":"%FOLDER%/%FILENAME%","Next":{"Command":"unrar","Arguments":"e -p- %PATH% %FOLDER%/%FILENAME%","Next":null}}},{"Regex":".*\\.zip","Process":{"Command":"mkdir","Arguments":"%FOLDER%/%FILENAME%","Next":{"Command":"unzip","Arguments":"%PATH% -d %FOLDER%/%FILENAME%","Next":null}}}]</value>
  </setting>
```

You can also create it with the GUI in the settings.
